### Intro to Tensors

Tensors are the fundamental building blocks of neural networks in PyTorch. Similar to NumPy arrays, tensors act as storage containers for numerical data.


In [2]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn

In [3]:
# create a numpy array with the rent in US dollars, size in square feet, and age in years
apt_array = np.array([2550, 750, 3.5])
# convert to a tensor of floats
apt_tensor = torch.tensor(
    apt_array, 
    dtype=torch.float)


In [4]:
# create a pandas dataframe with the rent in US dollars, size in square feet, and age in years
df = pd.read_csv("../../assets/csv/streeteasy.csv")
df = df[["rent", "size_sqft", "building_age_yrs"]]

# convert to a tensor of floats
df_tensor = torch.tensor(df.values, dtype=torch.float32)   

# print the tensors
df_tensor

tensor([[2.5500e+03, 4.8000e+02, 1.7000e+01],
        [1.1500e+04, 2.0000e+03, 9.6000e+01],
        [3.0000e+03, 1.0000e+03, 1.0600e+02],
        ...,
        [1.6990e+03, 2.5000e+02, 9.6000e+01],
        [3.4750e+03, 6.5100e+02, 1.4000e+01],
        [4.5000e+03, 8.1600e+02, 9.0000e+00]])

#### Linear Regression with Perceptrons

A Perceptron is a type of network structure consisting of **nodes** connected to each other by **edges**. The nodes appear in vertical layers, connected from left to right.


In [5]:
# Define the inputs
size_sqft = 1250.0
age = 15.0
bedrooms = 2.0

# The inputs flow through the edges, receiving weights
w_size = 3*size_sqft
w_age = -2.3*age
w_bedrooms = 100*bedrooms
bias = 500


# The output node adds the weighted inputs
weighted_sum = w_size + w_age + w_bedrooms + bias

# Generate prediction
print("Predicted Rent:", weighted_sum)

Predicted Rent: 4415.5


#### Activation Functions

One of the ways neural networks move beyond linear regression is by incorporating non-linear activation functions. These functions allow a neural network to model nonlinear relationships within a dataset, which are very common and cannot be modeled with linear regression.

##### ReLU Activation Function

One of the most common activation functions used in neural networks is called ReLU.

If a number is negative, ReLU returns 0. If a number is positive, ReLU returns the number with no changes.


In [6]:
# define the ReLU function
def ReLU(x):
    return max(0,x)

# apply the ReLU function to the weighted sum
ReLU_output = ReLU(-2 + 1 + .5)

# show output
ReLU_output

0

#### Build a Sequential Neural Network

Now that we know the basic structure of a neural network, let’s build one in PyTorch using PyTorch’s Sequential container.


- input layer: three nodes
- hidden layer: eight nodes, with ReLU activation
- output layer: one node


In [7]:
# set the random seed for reproducibility
torch.manual_seed(42)

# create a model with 3 inputs, 8 neurons in the hidden layer, and 1 output
model = nn.Sequential(
    nn.Linear(3,8),
    nn.ReLU(),
    nn.Linear(8,1)
)

# show model details
model

Sequential(
  (0): Linear(in_features=3, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

##### Dataset Import


In [11]:
# load pandas DataFrame
apartments_df = pd.read_csv("../../assets/csv/streeteasy.csv")

# create a numpy array of the numeric columns
apartments_numpy = apartments_df[['size_sqft', 'bedrooms', 'building_age_yrs']].values

# convert to an input tensor
X = torch.tensor(apartments_numpy,dtype=torch.float32)

# preview the first five apartments
X[:5]

tensor([[4.8000e+02, 0.0000e+00, 1.7000e+01],
        [2.0000e+03, 2.0000e+00, 9.6000e+01],
        [1.0000e+03, 3.0000e+00, 1.0600e+02],
        [9.1600e+02, 1.0000e+00, 2.9000e+01],
        [9.7500e+02, 1.0000e+00, 3.1000e+01]])

In [13]:
# set a random seed - do not modify
torch.manual_seed(42)

# define the neural network
model = nn.Sequential(
    nn.Linear(3,16),
    nn.ReLU(),
    nn.Linear(16,8),
    nn.ReLU(),
    nn.Linear(8,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

## YOUR SOLUTION HERE ##
predicted_rent = model(X)

# show output
predicted_rent[:5]

tensor([[ -6.9229],
        [-29.8163],
        [-16.0748],
        [-13.2427],
        [-14.1096]], grad_fn=<SliceBackward0>)

#### Build a Neural Network Class
While ``nn.Sequential`` is pretty useful for creating neural networks, often AI developers need to create non-sequential types of neural networks using object-oriented programming (OOP).
