## Linear Algebra

### Using NumPy Arrays
The core of using NumPy effectively for linear algebra is using NumPy arrays. NumPy arrays are n-dimensional array data structures that can be used to represent both vectors (1-dimensional array) and matrices (2-dimensional arrays).

In [3]:
import numpy as np

# Given vectors
vector_1 = np.array([-2,-6,2,3])
vector_2 = np.array([4,1,-3,8])
vector_3 = np.array([5,-7,9,0])

# Matrices can be created by combining existing vectors using the np.column_stack() function
matrix = np.column_stack((vector_1, vector_2, vector_3))
print(matrix)

# To access the shape of a matrix or vector, we call the .shape attribute of the array variable
print(matrix.shape)

second_column = matrix[:, 2]
print(second_column)



[[-2  4  5]
 [-6  1 -7]
 [ 2 -3  9]
 [ 3  8  0]]
(4, 3)
[ 5 -7  9  0]


### Using NumPy for Linear Algebra Operations

In [5]:
# Given
# 2 x 3 matrix
A = np.array([[2,3,-4], [-2, 1, -3]])
# 2 x 3 matrix
B = np.array([[1,-1,4], [3,-3,3]])
# 3 x 2 matrix
C = np.array([[1, 2], [3, 4], [5, 6]])

# Calculate D = 4A - 2B
D = 4*A - 2*B
print("4A - 2B:\n",D)

# Calculate E = AC
E = A@C
print("AC:\n",E)

# Calculate F = CA
F = C@A
print("CA:\n",F)


4A - 2B:
 [[  6  14 -24]
 [-14  10 -18]]
AC:
 [[ -9  -8]
 [-14 -18]]
CA:
 [[ -2   5 -10]
 [ -2  13 -24]
 [ -2  21 -38]]


### Special Matrices
In addition to having built-in support for many linear algebra-related operations, Let’s see how NumPy can create special matrices, such as the identity matrix.


In [7]:
# Given
A = np.array([[1,-1,1], [0,1,0], [-1,2,1]])
B = np.array([[0.5,1.5,-0.5], [0,1,0], [0.5,-0.5,0.5]])

# Find the matrix product AB and BA, and determine what that product says about A and B.
print(np.matmul(A,B))
print(B@A)

# Find the transpose of matrix A and matrix B
print(A.T)
print(B.T)

zero_vector = np.zeros((5))
identity = np.eye(4)
zero_matrix = np.zeros((3,2))

print(zero_matrix)
print(zero_vector)
print(identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1  0 -1]
 [-1  1  2]
 [ 1  0  1]]
[[ 0.5  0.   0.5]
 [ 1.5  1.  -0.5]
 [-0.5  0.   0.5]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Additional Linear Algebra Operations

Moving past special matrices, there are some more advanced linear algebra operations we can perform using NumPy. To start, we will be using the `numpy.linalg` sublibrary to perform the following operations:


In [8]:
# Represent the following system in NumPy matrix/vector form, then solve for x, y, and z

# Given
'''
4x + z = 2
-y + 2z - 3x = 0
.5y - x - 1.5z = -4
'''

# Answer 1
A = np.array([[4, 0, 1],[-3, -1, 2],[-1, 0.5, -1.5]])

# Answer 2
b = np.array([2, 0, -4])

# Answer 3
x,y,z = np.linalg.solve(A,b)
print((x,y,z))


(6.0, -62.0, -22.0)
